//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1._1
{
    using System;
    using System.Collections.Generic;
    
    public  partial class Inventory
    {
        public int Serial { get; set; }
        public string Item_Name { get; set; }
        public  Nullable<int> Item_Quantity { get; set; }
        public  Nullable<int> Quantity_Sold { get; set; }
        public  Nullable<int> Unit_Price { get; set; }
    }
}
